name: Making Website
on:
  push:
  workflow_dispatch:

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies for join form
        run: npm i & npm run build
        working-directory: join

      - name: Install dependencies for order form
        run: npm i & npm run build
        working-directory: order

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated Update'
