name: Making Website
on:
  push:
  workflow_dispatch:

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm i

      - name: Building join form
        working-directory: join
        run: npm run build

      - name: Building order form
        working-directory: join
        run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated Update'
