name: Making Website
on:
  push:
  workflow_dispatch:

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: join form
        run: npm i && npm run build
        working-directory: join

      - name: order form
        run: npm i && npm run build
        working-directory: order

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
